version: 0.1
component: build
timeoutInSeconds: 6000
runAs: root
shell: bash
env:
  variables:
    "minor_version" : "20"
    "testEnv" : "testEnvValue1"
  exportedVariables:
    - testEnv
    - minor_version
#  vaultVariables:
#    "bankPassword": "ocid1.vaultsecret.oc1.iad.amaaaaaa34lgq7aa325l6x7exbl5y7c4pk75aodriekuttjkuqatetll35aq"       # secret-id (in OCI ID format) STORED IN OCI Vault Service
# inputArtifacts:
#   - name: hello-dev-jar
#     location: hello123.class

steps:
  - type: Command
    name: "Build Source 1"
    timeoutInSeconds: 400
    command: |
      echo "hello world"
      echo $minor_version
      minor_version=22
  - type: Command
    name: "Build Source 2"
    timeoutInSeconds: 400
    command: |
      echo "hello world"
      echo $minor_version
outputArtifacts:
  - name: ABC
    type: BINARY
    location: abc.txt
